train:
  log_clearml: True
  epochs: 500
  task_name: new_data_6_channels_norm
  model_save_path: new_data_6_channels_norm
dataloader:
  weighted_sampler: True
  augmentations_intensity: 0.8
  data_dir: /home/alenaastrakhantseva/PycharmProjects/tick_tick_bloom/data/arrays/more_arrays_fixed
  csv_path: /home/alenaastrakhantseva/PycharmProjects/tick_tick_bloom/data/splits/downloaded.csv
  test_size: 0
  batch_size: 32
  save_preprocessed: "/home/alenaastrakhantseva/PycharmProjects/tick_tick_bloom/data/preprocessed/test"
net:
  resume_weights: ""
  freeze_grads: False
  pretrained: True
  model_name: rexnet-100
  new_in_channels: 6
optimizer:
  optimizer_name: adam
  lr: 0.0003
scheduler:
  scheduler: True
  t0: 1
  t_mult: 2