train:
  log_clearml: True
  epochs: 500
  task_name: weighted_sampler_adam
  model_save_path: weighted_sampler_adam
dataloader:
  weighted_sampler: True
  augmentations_intensity: 0.8
  data_dir: /home/alenaastrakhantseva/PycharmProjects/tick_tick_bloom/data/benchmark/image_arrays
  csv_path: /home/alenaastrakhantseva/PycharmProjects/tick_tick_bloom/data/splits/balanced_validation/dumb_split_full_df.csv
  test_size: 0
  batch_size: 32
net:
  resume_weights: ""
  freeze_grads: False
  pretrained: True
  model_name: resnet18
optimizer:
  optimizer_name: adam
  lr: 0.001
scheduler:
  scheduler: True
  t0: 1
  t_mult: 2